// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7M9vN0zf5QhixkOk-leaRvTs_IUW9Icg',
    appId: '1:1052293924427:web:2f568938ceb7df768befce',
    messagingSenderId: '1052293924427',
    projectId: 'mathclash-7474b',
    authDomain: 'mathclash-7474b.firebaseapp.com',
    storageBucket: 'mathclash-7474b.firebasestorage.app',
    measurementId: 'G-4CMZRN1C8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqcl3q3Kok5p7su-duxhM2OXxfq611kM',
    appId: '1:1052293924427:android:ecc93081547537f28befce',
    messagingSenderId: '1052293924427',
    projectId: 'mathclash-7474b',
    storageBucket: 'mathclash-7474b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDaKYV8pzXR9240iVn0FhlUAmdhwm01k',
    appId: '1:1052293924427:ios:f000d1ca6da05bf38befce',
    messagingSenderId: '1052293924427',
    projectId: 'mathclash-7474b',
    storageBucket: 'mathclash-7474b.firebasestorage.app',
    iosBundleId: 'com.example.mathClash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWDaKYV8pzXR9240iVn0FhlUAmdhwm01k',
    appId: '1:1052293924427:ios:f000d1ca6da05bf38befce',
    messagingSenderId: '1052293924427',
    projectId: 'mathclash-7474b',
    storageBucket: 'mathclash-7474b.firebasestorage.app',
    iosBundleId: 'com.example.mathClash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7M9vN0zf5QhixkOk-leaRvTs_IUW9Icg',
    appId: '1:1052293924427:web:f70c51dae0f813378befce',
    messagingSenderId: '1052293924427',
    projectId: 'mathclash-7474b',
    authDomain: 'mathclash-7474b.firebaseapp.com',
    storageBucket: 'mathclash-7474b.firebasestorage.app',
    measurementId: 'G-RN796J66JT',
  );
}
